# A sample Gemfile
source "https://rubygems.org"

gem "rack"
gem "thor"
gem "sprockets"
gem "sprockets-sass"
gem "thin"
gem "coffee-script"
gem "sass", "~>3.2.0.alpha.277"
gem "compass"
gem "compass-sprockets", :git => "git://github.com/heygrady/compass-sprockets.git"
gem "stylus", :git => "git://github.com/maccman/ruby-stylus.git"
gem "haml"
gem "guard"
gem "guard-haml"
gem "foreman"
gem "haml-sprockets", :git => "git://github.com/davidjbeveridge/haml-sprockets.git"
gem "json"
